In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('restaurant_data_with_features.csv')

In [4]:
df

,r_id,r_name,city,r_rating,r_rating_count,avg_price_per_person,cuisine,f_id,avg_price_per_item,f_name,...,ValueIndex,PremiumLabel,HealthLabel,NewOrSeasonal,PromoIneligible,MenuSize,AvgItemRatingPerRestaurant,PriceRange,RatingGap,CuisineCityCount
0,567335.0,AB FOODS POINT,Abohar,1.9,20,200.0,"Beverages,Pizzas",fd0,40.0,Aloo Tikki Burger,...,1196.0,1,0,0,0,131,3.845802,1595.16,2.1,3
1,567335.0,AB FOODS POINT,Abohar,2.0,15,200.0,"Beverages,Pizzas",fd669322,40.0,Aloo Tikki Burger,...,1365.0,1,0,0,0,131,3.845802,1595.16,1.9,3
2,567335.0,AB FOODS POINT,Abohar,2.7,18,200.0,"Beverages,Pizzas",fd1,50.0,Veg Creamy Burger,...,1152.6,1,0,0,0,131,3.845802,1595.16,0.7,3
3,567335.0,AB FOODS POINT,Abohar,2.0,12,200.0,"Beverages,Pizzas",fd2,65.0,Cheese Burst Burger,...,2679.0,0,0,0,1,131,3.845802,1595.16,1.8,3
4,567335.0,AB FOODS POINT,Abohar,1.3,10,200.0,"Beverages,Pizzas",fd3,80.0,Paneer Creamy Burger,...,1396.0,0,0,0,1,131,3.845802,1595.16,2.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063883,96525.0,IceBreakers Ice Cream,"HSR,Bangalore",3.4,34,200.0,"Ice Cream,Desserts",fd1048555,300.0,Sizzlers De- Verdure,...,666.0,1,0,0,0,57,3.819298,1133.60,0.3,13
1063884,96525.0,IceBreakers Ice Cream,"HSR,Bangalore",3.4,48,200.0,"Ice Cream,Desserts",fd1048556,300.0,Veg Bbq Sizzler,...,1161.0,0,0,0,0,57,3.819298,1133.60,0.9,13
1063885,96525.0,IceBreakers Ice Cream,"HSR,Bangalore",3.4,39,200.0,"Ice Cream,Desserts",fd1048558,350.0,Veg Sizzling Italian,...,736.3,1,0,0,0,57,3.819298,1133.60,0.3,13
1063886,96525.0,IceBreakers Ice Cream,"HSR,Bangalore",3.4,23,200.0,"Ice Cream,Desserts",fd1048561,200.0,Veg Overload Sandwich,...,1033.6,1,0,0,0,57,3.819298,1133.60,0.6,13
1063887,96525.0,IceBreakers Ice Cream,"HSR,Bangalore",3.4,38,200.0,"Ice Cream,Desserts",fd1048562,270.0,Aglio Riso Rice Bowl,...,1204.0,1,0,0,0,57,3.819298,1133.60,0.1,13

In [5]:
import pandas as pd

# Sample DataFrame creation (replace this with your actual data loading)
# df = pd.read_csv('your_data.csv')

# Split the cuisine column and create new columns
df[['cuisine_1', 'cuisine_2']] = df['cuisine'].str.split(',', n=1, expand=True)

# Remove any extra whitespace
df['cuisine_1'] = df['cuisine_1'].str.strip()
df['cuisine_2'] = df['cuisine_2'].str.strip()

# Display results
print(df.head())

       r_id          r_name    city  r_rating  r_rating_count  \
0  567335.0  AB FOODS POINT  Abohar       1.9              20
1  567335.0  AB FOODS POINT  Abohar       2.0              15
2  567335.0  AB FOODS POINT  Abohar       2.7              18
3  567335.0  AB FOODS POINT  Abohar       2.0              12
4  567335.0  AB FOODS POINT  Abohar       1.3              10

   avg_price_per_person           cuisine      f_id  avg_price_per_item  \
0                 200.0  Beverages,Pizzas       fd0                40.0
1                 200.0  Beverages,Pizzas  fd669322                40.0
2                 200.0  Beverages,Pizzas       fd1                50.0
3                 200.0  Beverages,Pizzas       fd2                65.0
4                 200.0  Beverages,Pizzas       fd3                80.0

                 f_name  ... HealthLabel  NewOrSeasonal  PromoIneligible  \
0     Aloo Tikki Burger  ...           0              0                0
1     Aloo Tikki Burger  ...           0              0                0
2     Veg Creamy Burger  ...           0              0                0
3   Cheese Burst Burger  ...           0              0                1
4  Paneer Creamy Burger  ...           0              0                1

  MenuSize  AvgItemRatingPerRestaurant  PriceRange  RatingGap  \
0      131                    3.845802     1595.16        2.1
1      131                    3.845802     1595.16        1.9
2      131                    3.845802     1595.16        0.7
3      131                    3.845802     1595.16        1.8
4      131                    3.845802     1595.16        2.7

   CuisineCityCount  cuisine_1  cuisine_2
0                 3  Beverages     Pizzas
1                 3  Beverages     Pizzas
2                 3  Beverages     Pizzas
3                 3  Beverages     Pizzas
4                 3  Beverages     Pizzas

[5 rows x 32 columns]

In [6]:
df.to_csv('new.csv', index=False)